esphome:
  name: ledpoi
  board: nodemcu-32s
  platform: esp32
  arduino_version: LATEST
  includes:
  - led.h
  libraries:
  - FastLED


custom_component:
  lambda: |-
    auto led = new Led();
    return {led};